# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
matrix:
  include:
  # We grab the appropriate GHC and cabal-install versions from hvr's PPA. See:
  # https://github.com/hvr/multi-ghc-travis
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=2.0
    compiler: ": #GHC 8.0.1"
    addons: {apt: {packages: [cabal-install-2.0,ghc-8.0.1,happy-1.19.5], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.2.2 CABALVER=2.0
    compiler: ": #GHC 8.2.2"
    addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2,happy-1.19.5], sources: [hvr-ghc]}}

  - env: BUILD=cabal GHCVER=8.4.3 CABALVER=2.2
    compiler: ": #GHC 8.4.3"
    addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.3,happy-1.19.5], sources: [hvr-ghc]}}


  # Build with the newest GHC and cabal-install. This is an accepted failure,
  # see below.
  # - env: BUILD=cabal GHCVER=head  CABALVER=head
  #   compiler: ": #GHC HEAD"
  #   addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: BUILD=stack ARGS="--resolver lts-12"
    compiler: ": #stack 8.4.3"
    addons: {apt: {packages: [ghc-8.4.3], sources: [hvr-ghc]}}

  # Nightly builds are allowed to fail
  # - env: BUILD=stack ARGS="--resolver nightly"
  #   compiler: ": #stack nightly"
  #   addons: {apt: {packages: [libgmp-dev]}}

  # - env: BUILD=stack ARGS="--resolver lts-8"
  # compiler: ": #stack 8.0.1 osx"
  # os: osx

  # - env: BUILD=stack ARGS="--resolver nightly"
  # - compiler: ": #stack nightly osx"
  # - os: osx

  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head
  - env: BUILD=stack ARGS="--resolver nightly"
  - env: BUILD=cabal GHCVER=8.2.2 CABALVER=2.0
  # 8.2.2 on Cabal always hangs on travis, for unknown reasons

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# We want to always allow newer versions of packages when building on GHC HEAD
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi

# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/happy/1.19.5/bin/:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack --no-terminal --install-ghc $ARGS build --test --only-dependencies --fast --flag "pandoc-citeproc:test_citeproc" --flag "pandoc-citeproc:embed_data_files" --flag "aeson:fast" --jobs 2
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --only-dependencies --enable-tests --force-reinstalls --disable-optimization -ffast --reorder-goals --max-backjumps=-1 $CABALARGS
      ;;
  esac

script:
- |
  case "$BUILD" in
    stack)
      ulimit -n 4096
      stack --no-terminal $ARGS test --haddock --no-haddock-deps --flag "pandoc-citeproc:test_citeproc" --flag "pandoc-citeproc:embed_data_files" --flag "aeson:fast" --fast --ghc-options="-Wall -fno-warn-unused-do-bind -Werror" --jobs 2 && \
      EC=$? && \
      (stack exec test-citeproc || echo "expected to fail...") && \
      exit $EC
      ;;
    cabal)
      cabal sdist --output-directory=sourcedist && \
      cd sourcedist && \
      cabal install --enable-tests -ffast --disable-optimization --ghc-options="-Wall -fno-warn-unused-do-bind -Werror" -j2 $CABALARGS && \
      cabal test
      ;;
  esac
